export const GET_LIST_SONG_REQUEST = "GET_LIST_SONG_REQUEST";
export const GET_LIST_SONG_SUCCESS = "GET_LIST_SONG_SUCCESS";
export const GET_LIST_SONG_FAIL = "GET_LIST_SONG_FAIL";
export const PLAY_SONG = "PLAY_SONG";

